---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx 
        state: present
        update_cache: yes
    - name: Install apache2
      apt:
        name: apache2 
        state: present
        update_cache: yes
    - name: Start and enable apache2 service (Debian-based)
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Copy content to index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>This is created using ansible</h1>"