---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
     
    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
    - name: Copy content to index
      copy:
        dest: {{file_output.diff.before.path}}
        content: "<h1>This is created using ansible</h1>"