---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
     
    - name: Create user franck
      user:
        name: bang
        comment: kef Smith
        shell: /bin/bash
    - name: Create group
      group:
        name: cloudteam
        state: absent
    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags:
        - a
        - b
        - c
    - name: Read data
      debug:
        var: file_output.diff.before.path
    - name: Create directory
      file:
        path: /tmp/os
        state: directory
    - name: Copy content to index
      copy:
        dest: file_output.diff.before.path
        content: "<h1>This is created using ansible</h1>"